### ISSUE TITLE
FeatureRequest: getCodeFromLn

### ISSUE THREAD

**Issue by andre-dietrich** [ChristophP/elm-i18n-module-generator#1]
Thanks for this great and easy to use package. At them moment there is only the function `getLnFromCode`. Would it be possible to add some more convenience functions, such as:

Simply an inverted helper function that allows to retrieve the language string from the passed language:

``` elm
getCodeFromLn : Lang -> String
getCodeFromLn lang =
  case lang or
     De -> "de"
     En -> "en"
    ...
```

Something to check, if the language is supported? This way it would be possible to check an react slightly different if a language is not supported... Otherwise, it is required to maintain this list additionally and to update it with every additional translation.

``` elm
isSupported: String -> Bool
isSupported code =
  List.member code ["de", "en", ... ]
    ...
```

**Comment by ChristophP** [comment]
Hi @andre-dietrich ,
glad you are liking the package and I hope it helps you do what you need to to do translations with Elm.

I haven't really worked on this package for a long time, but I can see that `getCodeFromLn` and `isSupported` would be useful additions. I'm not planning on making changes myself to this repo, but I'll be happy to accept a PR if you are willing to provide one.

Some background on Elm and translations:
- When I got started with Elm in 2017 there was no real solution for translations that did what I wanted
- This was the first package that I made (a codegen approach with lots of type safety)
- After that I went on to create another package which was a bit easier and more flexible at the cost of some type safety. https://github.com/ChristophP/elm-i18next, with a more extensive API
- Another community member went on to make an additional package which adds type safety to the previous one with code gen https://github.com/yonigibbs/elm-i18next-gen

There are some trade-offs to considered depending on what you need. But maybe some those packages will already do what you need.

**Comment by andre-dietrich** [comment]
Hi, thanks for the information ... Unfortunately I would like to use your project as it is, only for simple title and alt attributes, nothing fancy and nothing big... I just added some of the convenience functions and added the ability to add a default language, which might also be useful for others, when translations do not exist for all languages...

Thank you anyways ;-)

**Comment by ChristophP** [comment]
Hi there, sorry for the long wait time. Last weeks have been busy. I'll take a quick look at your PR.

**Comment by ChristophP** [comment]
@andre-dietrich Hi sorry for the long wait time. I published the changes from your commit along a few more commits from myself as 1.2.0 . Let me know if everything works as expected for you.

**Comment by andre-dietrich** [comment]
Great, works perfectly ... thanks a lot ...

**Comment by ChristophP** [comment]
Sweet :-) Closing
